version: "~> 1.0"
git:
    depth: 1
    quiet: true
language: java
jdk:
    - openjdk21
branches:
    only:
        - develop
        - support/4.1
cache:
    directories:
        - "$HOME/.m2"
notifications:
    slack: craftersoftware:7YiSb41ZG5rfMgiAY7Qgprc7
before_install:
    - mkdir -p $HOME/.m2
    - cp .travis-settings.xml $HOME/.m2/settings.xml
install: skip
script:
    - if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then bash -c "mvn deploy --settings .travis-settings.xml"; fi
    - if [[ "$TRAVIS_PULL_REQUEST" != "false" ]]; then bash -c "mvn clean install"; fi
env:
    global:
        - secure: "JZqfipXJJNio7H+SBI17XFjQ2SKdMaxKW068fPnJO/Y95Rd/UzRxNXdAOFSsWoUTPxpKqMo9ulsybCdXzo4s7DPCZpovzu3ypcG/8PkJqh7xg6tGxT+ZEIWyh9quhmh/tKt8wvlMLosJZlE3Ff/j9giBskqPhG0VkjT+duB9FuI="
        - secure: "MGq+KjxAn9bvtAE2I0S+d8906xoXMn1idNywZyboNY9p7T7aKE46jlKi/jEqGtXYx8D+6L20Z+NXj18GTbDvnnLWiV+I7JUQdSH5VaBafMJO0GB9n2uVZ4piu/ObWRB3bwCcVrrCd3dXHmcvwoFcGc9qR9ONS6Io1pqRddiNxsw="
