version: "~> 1.0"
git:
    depth: 1
    quiet: true
language: java
jdk:
    - openjdk21
branches:
    only:
        - develop
        - support/4.1
cache:
    directories:
        - "$HOME/.m2"
notifications:
    slack: craftersoftware:7YiSb41ZG5rfMgiAY7Qgprc7
before_install:
    - mkdir -p $HOME/.m2
    - cp .travis-settings.xml $HOME/.m2/settings.xml
install: skip
script:
    - if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then bash -c "mvn deploy --settings .travis-settings.xml"; fi
    - if [[ "$TRAVIS_PULL_REQUEST" != "false" ]]; then bash -c "mvn clean install"; fi
env:
    global:
        - secure: "BGlCCDMmAvAAfhRHIA+5NBSp15Edvm2OyBsUmqGqcUyGMQPtgOS28Grcybxp5984JGPCRkAFrDGcTnTXvJyD4nz9bdzOh6lT4s2LF/Otjl6iCXV3ljOE2HPvtbG0vKUJPMFCf89QHyvAJVhKtsSUvvV5DPSKfH9RoaxtmrN4iOg="
        - secure: "Pw1QEB1JAwo63jE9kvn0VCF2fX76gV5S5ChTGaIqjGhEKi/qK0rpZccq1FIS5iUN4CM7jQV+l+Bt1nMV/XLb/3aTDMrbVZb+AelsDAFAJc0OlFsJRw8LcNIE6Amz8xtS+VvZb9x5s7cr9DyzNaw9I/L+//eK8UsiREhbex864LE="
